# Change these first
owner: smc # Your GitHub organization or username, where this repository lives
repo: upt # The name of this repository

sites:
  - name: LibIndic
    url: https://libindic.org/
  - name: Grandham
    url: https://grandham.in
  - name: Community
    url: https://community.smc.org.in
  - name: Volunteer
    url: https://volunteer.smc.org.in
assignees : # Users to assign downtime issues (optional)
  - balasankarc
  - joicemjoseph

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status2.smc.org.in
  baseUrl: /upt
  logoUrl: https://smc.org.in/img/logo.60277b3b.svg
  name: "SMC | Status"
  introTitle: "***SMC*** status log"
  introMessage: This status page for SMC websites
  navbar:
    - title: Status
      href: /
    - title: SMC
      href: https://smc.org.in

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration