# Change these first
owner: smc # Your GitHub organization or username, where this repository lives
repo: upt # The name of this repository

delay: 5000
sites:
  - name: LibIndic
    url: https://libindic.org/
    assignees: 
    - asdofindia
  - name: Grandham
    url: https://grandham.in
    assignees: 
    - tachyons
  - name: Poorna
    url: https://poorna.smc.org.in
    __dangerous__disable_verify_peer: true
    expectedStatusCodes: [200]
    maxResponseTime: 120000
    assignees: 
    - mujeebcpy
  - name: Community
    url: https://community.smc.org.in
    assignees: 
    - joicemjoseph
  - name: Volunteer
    url: https://volunteer.smc.org.in
    assignees: 
    - joicemjoseph
  - name: Morphology Analyser
    url: https://morph.smc.org.in
    __dangerous__disable_verify_peer: true
    expectedStatusCodes: [200]
    assignees: 
    - santhoshtr
  - name: Varnam API
    url: https://api.varnamproject.com/status
    __dangerous__disable_verify_peer: true
    expectedStatusCodes: [200]
    assignees: 
    - subins2000
  - name: KDE translation
    url: https://kde.smc.org.in/api/?format=json
    __dangerous__disable_verify_peer: true
    expectedStatusCodes: [200]
    assignees: 
    - subins2000
assignees : # Users to assign downtime issues (optional)
  - balasankarc
  - joicemjoseph

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.smc.org.in
  # baseUrl: /upt
  logoUrl: https://smc.org.in/img/logo.60277b3b.svg
  name: "Status Page"
  introTitle: "***SMC*** service status log"
  introMessage: This status page for SMC websites
  navbar:
    - title: Status
      href: /upt
    - title: SMC
      href: https://smc.org.in

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
